version: '3.8'

services:
  nginx:
    build: "./containers/nginx"
    restart: always
    ports:
      - "80:80"
    container_name: "nginx"
    networks:
      - app
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  node:
    build: "./containers/node"
    restart: always
    networks:
      - app
      - db
    volumes:
      - ./containers/node:/node
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - INSTANCE=node
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    build: "./containers/postgres"
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGUSER=${POSTGRES_USER}
    ports:
      - "5423:5432"
    networks:
      - db
    volumes:
      - ./containers/postgres/data:/var/lib/postgresql/data
      - ./containers/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_USER} -p 5432"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  app:
  db:
